import sys
import os
import locale

# 只在 Windows 系統上導入 windll
if sys.platform == 'win32':
    from ctypes import windll

# 手动语言设置 - 如果你想强制使用特定语言，请取消注释并设置以下变量
# 支持的语言代码: 'en', 'zh-tw', 'zh-cn', 'ja', 'it', 'de', 'no', 'es', 'fr'
# MANUAL_LANG = 'zh-cn'  # 取消注释此行并设置你想要的语言代码

TRANSLATIONS = {
    "en": {
        "open": "Open",
        "save": "Save",
        "next_image": "Next Image",
        "prev_image": "Previous Image",
        "delete": "Delete Selected Box(es)",
        "auto_save": "Auto Save",
        "label_propagation": "Label Propagation",
        "output_format": "Output Format",
        "classes": "Classes",
        "ready": "Ready",
        "no_classes_file": "No classes.txt found in this folder.\nWould you like to select an existing txt file as the class file?\nChoose Yes to select a file, or No to manually enter classes.",
        "yes": "Yes",
        "no": "No",
        "hotkeys_help": "Hotkeys Help",
        "quit": "Quit",
        "file_menu": "File(&F)",
        "load_label_file": "Load Label File (e.g., .txt)",
        "help_menu": "Help(&H)",
        "hotkeys_menu": "Hotkeys(&K)",
        "about_menu": "About BakuAI AS(&A)",
        "hotkeys_title": "Hotkeys Help",
        "hotkeys_list": "Hotkeys list：",
        "next_image_hotkey": "Next Image",
        "prev_image_hotkey": "Previous Image",
        "save_hotkey": "Save Annotations",
        "open_hotkey": "Open Directory",
        "delete_hotkey": "Delete Selected Box(es)",
        "quit_hotkey": "Quit",
        "label_propagation_hotkey": "Switch Label Propagation",
        "multi_select_hotkey": "Multi-select bounding boxes",
        "undo_hotkey": "Undo (per image labeling)",
        "redo_hotkey": "Redo (per image labeling)",
        "about_title": "About BakuAI",
        "version": "Version",
        "copyright": "Copyright Reserved",
        "website": "Official Website",
        "software_description": "This software is used for image labeling, supported for YOLO/VOC/COCO formats",
        "debug_info": "Debug Information",
        "current_working_dir": "Current Working Directory",
        "dist_dir_contents": "Dist Directory Contents",
        "debug_info_end": "Debug Information End",
        "class_save_failed": "Class Save Failed",
        "failed_to_write_classes": "Failed to write classes.txt: {0}",
        "save_error": "Save Error",
        "failed_to_save_yolo": "Failed to save YOLO annotations:\n{0}",
        "edit_label": "Edit Label",
        "enter_new_label": "Enter new label:",
        "data_aug_menu": "Data Augmentation(&D)",
        "data_aug_title": "Batch Data Augmentation",
        "saturation": "Saturation",
        "contrast": "Contrast",
        "brightness": "Brightness",
        "rotation": "Rotation (degrees)",
        "flip_ud": "Flip Up-Down",
        "flip_lr": "Flip Left-Right",
        "apply": "Apply",
        "cancel": "Cancel",
        "reset": "Reset",
        "preview": "Preview",
        "aug_per_image": "Augmentations per image",
        "output_folder": "Output Folder",
        "select_folder": "Select Folder",
        "processing": "Processing...",
        "aug_complete": "Augmentation Complete",
        "aug_progress": "Processing {0}/{1} images",
        "aug_success": "Successfully augmented {0} images",
        "aug_error": "Error during augmentation",
        "preserve_original": "Preserve Original Files",
        "aug_settings": "Augmentation Settings",
        "random_rotation": "Random Rotation Range",
        "random_brightness": "Random Brightness Range",
        "random_contrast": "Random Contrast Range",
        "random_saturation": "Random Saturation Range",
        "flip_options": "Flip Options",
        "warning": "Warning",
        "no_image": "No image loaded. Please open an image first.",
        "auto_label_menu": "Auto Label(&A)",
        "auto_label_title": "Visual Prompt Auto Labeling",
        "select_prompt_images": "Select Prompt Images",
        "select_target_image": "Select Target Image",
        "no_prompt_images": "No prompt images selected",
        "no_target_image": "No target image selected",
        "auto_label_error": "Auto labeling failed",
        "auto_label_success": "Auto labeling completed successfully",
        "enable_magnifier": "Enable Magnifier",
        "current_zoom": "Current Zoom: {0}x",
        "color_legend": "Color Legend",
        "load_custom_classes": "Load custom classes.txt",
        "to": "to",
        "unknown": "unknown",
        "error": "Error",
        "auto_label_all_unlabeled": "Auto Label All Unlabeled Images",
        "label_propagation_activated": "Label propagation activated",
        "label_propagation_disabled": "Label propagation disabled",
        "viewed": "Viewed",
        "index": "Index",
        "total": "Total",
        "error_current_dir_not_set": "Error: current_dir not set.",
        "bakuai_label_tool": "BakuFlow",
        "open_image_folder_to_start": "Open image folder to start",
        "logo_not_found_using_default": "Logo not found at {0}, using default.",
        "yoloe_wrapper_not_initialized": "YOLOEWrapper not initialized, please ensure class file is loaded",
        "batch_auto_label_start": "Starting batch auto labeling...",
        "batch_auto_label_complete": "Batch auto labeling completed",
        "select_prompt_images_first": "Please select prompt images first (green ones on the left)",
        "overwrite_labeled_images": "Overwrite labeled images?",
        "overwrite_labeled_images_question": "Do you want to overwrite already labeled images?",
        "all_images_labeled": "All images are already labeled, no need for auto labeling.",
        "auto_label_progress_title": "Auto Labeling Progress",
        "auto_label_preparing": "Preparing auto labeling...",
        "auto_label_validating": "Validating input files...",
        "auto_label_building_vpe": "Building visual prompt encoder...",
        "auto_label_setting_classes": "Setting classes and preparing prediction...",
        "auto_label_predicting": "Executing target image prediction...",
        "auto_label_completed_success": "✅ Auto labeling completed!\nSuccessfully processed {0}/{1} images",
        "auto_label_completed_partial": "⚠️ Auto labeling completed\nSuccessfully processed {0}/{1} images",
        "auto_label_failed_error": "❌ Auto labeling failed\nError: {0}",
        "delete_class": "Delete Class",
        "confirm_delete_class_title": "Confirm Delete Class",
        "confirm_delete_class_msg": "Are you sure you want to delete the class '{0}'?\nThis action cannot be undone.",
        "delete_related_annotations_title": "Delete Related Annotations",
        "delete_related_annotations_msg": "Found {0} annotations using class '{1}' in current image.\nDo you want to delete these annotations as well?",
        "auto_label_current_image": "Auto Label Current Image",
        "auto_label_current_title": "Auto Label Current Image",
        "auto_label_current_confirm": "Use current image annotations as prompts to auto-label the same image?\nThis will help find similar objects in the current image.",
        "no_current_image": "No current image loaded",
        "current_image_no_annotations": "Current image has no annotations to use as prompts",
        "failed_to_build_visuals": "Failed to build visual prompts from current annotations",
        "replace_annotations_title": "Replace Annotations",
        "replace_annotations_msg": "Do you want to replace existing annotations with new predictions?\nChoose 'No' to add new predictions to existing annotations.",
        "auto_label_current_success": "Current image auto labeling completed!\nAdded {0} new annotations.",
        "switch_project_title": "Switch Project",
        "switch_project_confirm": "Current work may be lost. Are you sure you want to switch to a new project?",
        "project_loaded": "Project '{0}' loaded with {1} images",
        "refresh_data": "Refresh Data",
        "refresh_data_tooltip": "Refresh project data and rescan annotation files",
        "project_info": "Project Information",
        "current_project": "Current Project",
        "total_images": "Total Images",
        "labeled_images": "Labeled Images",
        "unlabeled_images": "Unlabeled Images",
        "no_labeled_images_found": "No labeled images found in current project",
        "objects": "objects",
        "refresh_complete": "Refresh Complete",
        "refresh_complete_msg": "Found {0} labeled images in current project",
    },
    "zh-tw": {
        "open": "開啟",
        "save": "儲存",
        "next_image": "下一張圖片",
        "prev_image": "上一張圖片",
        "delete": "刪除選取框",
        "auto_save": "自動儲存",
        "label_propagation": "標籤傳播",
        "output_format": "輸出格式",
        "classes": "類別",
        "ready": "就緒",
        "no_classes_file": "此資料夾下找不到 classes.txt，是否要選擇現有的 txt 檔作為類別檔？\n選是可選檔，選否可自行輸入類別。",
        "yes": "是",
        "no": "否",
        "hotkeys_help": "快捷鍵說明",
        "quit": "離開",
        "file_menu": "檔案(&F)",
        "load_label_file": "載入標籤檔 (例如：.txt)",
        "help_menu": "說明(&H)",
        "hotkeys_menu": "快捷鍵(&K)",
        "about_menu": "關於 BakuAI AS(&A)",
        "hotkeys_title": "快捷鍵說明",
        "hotkeys_list": "快捷鍵列表：",
        "next_image_hotkey": "下一張圖片",
        "prev_image_hotkey": "上一張圖片",
        "save_hotkey": "儲存標註",
        "open_hotkey": "開啟資料夾",
        "delete_hotkey": "刪除選取框",
        "quit_hotkey": "離開",
        "label_propagation_hotkey": "切換標籤傳播",
        "multi_select_hotkey": "多選標註框",
        "undo_hotkey": "復原 (每張圖片獨立)",
        "redo_hotkey": "重做 (每張圖片獨立)",
        "about_title": "關於 BakuAI",
        "version": "版本",
        "copyright": "版權所有",
        "website": "官方網站",
        "software_description": "本軟體用於影像標註，支援 YOLO/VOC/COCO 格式",
        "debug_info": "除錯資訊",
        "current_working_dir": "目前工作目錄",
        "dist_dir_contents": "發佈目錄內容",
        "debug_info_end": "除錯資訊結束",
        "class_save_failed": "類別儲存失敗",
        "failed_to_write_classes": "無法寫入 classes.txt：{0}",
        "save_error": "儲存錯誤",
        "failed_to_save_yolo": "儲存 YOLO 標註失敗：\n{0}",
        "edit_label": "編輯標籤",
        "enter_new_label": "輸入新標籤：",
        "data_aug_menu": "資料增強(&D)",
        "data_aug_title": "批次資料增強",
        "saturation": "飽和度",
        "contrast": "對比度",
        "brightness": "亮度",
        "rotation": "旋轉角度",
        "flip_ud": "上下翻轉",
        "flip_lr": "左右翻轉",
        "apply": "套用",
        "cancel": "取消",
        "reset": "重設",
        "preview": "預覽",
        "aug_per_image": "每張圖片的增強數量",
        "output_folder": "輸出資料夾",
        "select_folder": "選擇資料夾",
        "processing": "處理中...",
        "aug_complete": "資料增強完成",
        "aug_progress": "處理第 {0}/{1} 張圖片",
        "aug_success": "成功增強 {0} 張圖片",
        "aug_error": "資料增強過程發生錯誤",
        "preserve_original": "保留原始檔案",
        "aug_settings": "增強設定",
        "random_rotation": "隨機旋轉範圍",
        "random_brightness": "隨機亮度範圍",
        "random_contrast": "隨機對比度範圍",
        "random_saturation": "隨機飽和度範圍",
        "flip_options": "翻轉選項",
        "warning": "警告",
        "no_image": "尚未載入圖片，請先開啟圖片。",
        "auto_label_menu": "自動標註(&A)",
        "auto_label_title": "視覺提示自動標註",
        "select_prompt_images": "選擇提示圖片",
        "select_target_image": "選擇目標圖片",
        "no_prompt_images": "尚未選擇提示圖片",
        "no_target_image": "尚未選擇目標圖片",
        "auto_label_error": "自動標註失敗",
        "auto_label_success": "自動標註完成",
        "error_no_class_list": "錯誤：未在主視窗中找到類別列表 (label_hist)",
        "error_target_image_not_exist": "錯誤：目標圖像不存在：{0}",
        "error_prompt_image_not_exist": "錯誤：提示圖像不存在：{0}",
        "processing_vp_auto_label": "正在處理視覺提示自動標註...",
        "converting_annotations": "正在轉換標註...",
        "executing_prediction": "正在執行預測...",
        "warning_unknown_class_id": "警告：未知類別ID {0}",
        "error_adding_bbox": "添加邊界框時出錯：{0}",
        "error_loading_annotation": "載入標註檔案失敗：{0}",
        "info_using_pascal_voc_reader": "資訊：使用 Pascal VOC 讀取器",
        "info_using_yolo_reader": "資訊：使用 YOLO 讀取器",
        "warning_no_compatible_reader": "警告：未找到相容的標註讀取器",
        "warning_no_annotation_file": "警告：未找到標註檔案：{0}",
        "warning_no_valid_annotations": "警告：未找到有效標註：{0}",
        "warning_unknown_class": "警告：未知類別 {0}",
        "warning_invalid_bbox_coords": "警告：無效的邊界框座標 [{0}, {1}, {2}, {3}]",
        "warning_cannot_get_bbox_coords": "警告：無法獲取邊界框座標，跳過標註",
        "error_processing_annotation": "處理標註檔案 {0} 時出錯：{1}",
        "auto_label_completed": "自動標註完成：添加了 {0} 個標註",
        "skipped_invalid_labels": "，跳過 {0} 個無效標註",
        "auto_label_completed_no_valid_labels": "自動標註完成，但未添加任何有效標註",
        "auto_label_failed": "自動標註失敗：{0}",
        "enable_magnifier": "啟用放大鏡",
        "current_zoom": "當前倍率：{0}x",
        "color_legend": "顏色圖例",
        "load_custom_classes": "載入自訂 classes.txt",
        "to": "到",
        "unknown": "未知",
        "error": "錯誤",
        "auto_label_all_unlabeled": "自動標註所有未標註圖片",
        "label_propagation_activated": "標籤傳播已啟用",
        "label_propagation_disabled": "標籤傳播已停用",
        "viewed": "已檢視",
        "index": "索引",
        "total": "總計",
        "error_current_dir_not_set": "錯誤：未設定當前目錄。",
        "bakuai_label_tool": "BakuAI 標註工具",
        "open_image_folder_to_start": "開啟圖片資料夾以開始",
        "logo_not_found_using_default": "在 {0} 找不到標誌，使用預設。",
        "yoloe_wrapper_not_initialized": "YOLOEWrapper 未初始化，請確保已加載類別文件",
        "batch_auto_label_start": "開始批量自動標註...",
        "batch_auto_label_complete": "批量自動標註完成",
        "select_prompt_images_first": "請先選擇提示圖片（左側綠色的圖片）",
        "overwrite_labeled_images": "覆蓋已標註圖片？",
        "overwrite_labeled_images_question": "你要覆蓋已經標註的圖片嗎？",
        "all_images_labeled": "所有圖片都已標註，無需自動標註。",
        "auto_label_progress_title": "自動標註進度",
        "auto_label_preparing": "準備自動標註...",
        "auto_label_validating": "驗證輸入文件...",
        "auto_label_building_vpe": "構建視覺提示編碼器...",
        "auto_label_setting_classes": "設置類別並準備預測...",
        "auto_label_predicting": "執行目標圖像預測...",
        "auto_label_completed_success": "✅ 自動標註完成！\n成功處理了 {0}/{1} 張圖片",
        "auto_label_completed_partial": "⚠️ 自動標註完成\n成功處理了 {0}/{1} 張圖片",
        "auto_label_failed_error": "❌ 自動標註失敗\n錯誤：{0}",
        "delete_class": "刪除類別",
        "confirm_delete_class_title": "確認刪除類別",
        "confirm_delete_class_msg": "你確定要刪除類別 '{0}' 嗎？\n此操作無法撤銷。",
        "delete_related_annotations_title": "刪除相關標註",
        "delete_related_annotations_msg": "在當前圖片中發現 {0} 個使用類別 '{1}' 的標註。\n你要一起刪除這些標註嗎？",
        "auto_label_current_image": "自動標註當前圖片",
        "auto_label_current_title": "自動標註當前圖片",
        "auto_label_current_confirm": "使用當前圖片的標註作為提示來自動標註同張圖片？\n這將幫助在當前圖片中找到相似的物體。",
        "no_current_image": "沒有加載當前圖片",
        "current_image_no_annotations": "當前圖片沒有標註可用作提示",
        "failed_to_build_visuals": "無法從當前標註構建視覺提示",
        "replace_annotations_title": "替換標註",
        "replace_annotations_msg": "你要用新的預測結果替換現有標註嗎？\n選擇'否'將新預測添加到現有標註中。",
        "auto_label_current_success": "當前圖片自動標註完成！\n添加了 {0} 個新標註。",
        "switch_project_title": "切換項目",
        "switch_project_confirm": "當前工作可能會丟失。你確定要切換到新項目嗎？",
        "project_loaded": "項目 '{0}' 已加載，包含 {1} 張圖片",
        "refresh_data": "刷新數據",
        "refresh_data_tooltip": "刷新項目數據並重新掃描標註文件",
        "project_info": "項目信息",
        "current_project": "當前項目",
        "total_images": "總圖片數",
        "labeled_images": "已標註圖片",
        "unlabeled_images": "未標註圖片",
        "no_labeled_images_found": "在當前項目中沒有找到已標註的圖片",
        "objects": "個對象",
        "refresh_complete": "刷新完成",
        "refresh_complete_msg": "在當前項目中找到 {0} 張已標註的圖片",
    },
    "zh-cn": {
        "open": "打开",
        "save": "保存",
        "next_image": "下一张图片",
        "prev_image": "上一张图片",
        "delete": "删除选中框",
        "auto_save": "自动保存",
        "label_propagation": "标签传播",
        "output_format": "输出格式",
        "classes": "类别",
        "ready": "就绪",
        "no_classes_file": "此文件夹下找不到 classes.txt，是否选择已有 txt 文件作为类别文件？\n选择是可选文件，选择否可手动输入类别。",
        "yes": "是",
        "no": "否",
        "hotkeys_help": "快捷键说明",
        "quit": "退出",
        "file_menu": "文件(&F)",
        "load_label_file": "加载标签文件 (例如：.txt)",
        "help_menu": "帮助(&H)",
        "hotkeys_menu": "快捷键(&K)",
        "about_menu": "关于 BakuAI AS(&A)",
        "hotkeys_title": "快捷键说明",
        "hotkeys_list": "快捷键列表：",
        "next_image_hotkey": "下一张图片",
        "prev_image_hotkey": "上一张图片",
        "save_hotkey": "保存标注",
        "open_hotkey": "打开文件夹",
        "delete_hotkey": "删除选中框",
        "quit_hotkey": "退出",
        "label_propagation_hotkey": "切换标签传播",
        "multi_select_hotkey": "多选标注框",
        "undo_hotkey": "撤销 (每张图片独立)",
        "redo_hotkey": "重做 (每张图片独立)",
        "about_title": "关于 BakuAI",
        "version": "版本",
        "copyright": "版权所有",
        "website": "官方网站",
        "software_description": "本软件用于图像标注，支持 YOLO/VOC/COCO 格式",
        "debug_info": "调试信息",
        "current_working_dir": "当前工作目录",
        "dist_dir_contents": "Dist 目录内容",
        "debug_info_end": "调试信息结束",
        "class_save_failed": "类别保存失败",
        "failed_to_write_classes": "无法写入 classes.txt：{0}",
        "save_error": "保存错误",
        "failed_to_save_yolo": "保存 YOLO 标注失败：\n{0}",
        "edit_label": "编辑标签",
        "enter_new_label": "输入新标签：",
        "data_aug_menu": "数据增强(&D)",
        "data_aug_title": "数据增强设置",
        "saturation": "饱和度",
        "contrast": "对比度",
        "brightness": "亮度",
        "rotation": "旋转角度",
        "flip_ud": "上下翻转",
        "flip_lr": "左右翻转",
        "apply": "应用",
        "cancel": "取消",
        "reset": "重置",
        "preview": "预览",
        "aug_per_image": "每张图片的增强数量",
        "output_folder": "输出资料夹",
        "select_folder": "选择资料夹",
        "processing": "处理中...",
        "aug_complete": "增强完成",
        "aug_progress": "处理第 {0}/{1} 张图片",
        "aug_success": "{0} 张图片增强成功",
        "aug_error": "增强过程中发生错误",
        "preserve_original": "保留原始文件",
        "aug_settings": "增强设置",
        "random_rotation": "随机旋转范围",
        "random_brightness": "随机亮度范围",
        "random_contrast": "随机对比度范围",
        "random_saturation": "随机饱和度范围",
        "flip_options": "翻转选项",
        "warning": "警告",
        "no_image": "尚未加载图片，请先打开图片。",
        "auto_label_menu": "自动标注(&A)",
        "auto_label_title": "视觉提示自动标注",
        "select_prompt_images": "选择提示图片",
        "select_target_image": "选择目标图片",
        "no_prompt_images": "尚未选择提示图片",
        "no_target_image": "尚未选择目标图片",
        "auto_label_error": "自动标注失败",
        "auto_label_success": "自动标注完成",
        "error_no_class_list": "错误：未在主窗口中找到类别列表 (label_hist)",
        "error_target_image_not_exist": "错误：目标图像不存在：{0}",
        "error_prompt_image_not_exist": "错误：提示图像不存在：{0}",
        "processing_vp_auto_label": "正在处理视觉提示自动标注...",
        "converting_annotations": "正在转换标注...",
        "executing_prediction": "正在执行预测...",
        "warning_unknown_class_id": "警告：未知类别ID {0}",
        "error_adding_bbox": "添加边界框时出错：{0}",
        "error_loading_annotation": "加载标注文件失败：{0}",
        "info_using_pascal_voc_reader": "信息：使用 Pascal VOC 读取器",
        "info_using_yolo_reader": "信息：使用 YOLO 读取器",
        "warning_no_compatible_reader": "警告：未找到兼容的标注读取器",
        "warning_no_annotation_file": "警告：未找到标注文件：{0}",
        "warning_no_valid_annotations": "警告：未找到有效标注：{0}",
        "warning_unknown_class": "警告：未知类别 {0}",
        "warning_invalid_bbox_coords": "警告：无效的边界框坐标 [{0}, {1}, {2}, {3}]",
        "warning_cannot_get_bbox_coords": "警告：无法获取边界框坐标，跳过标注",
        "error_processing_annotation": "处理标注文件 {0} 时出错：{1}",
        "auto_label_completed": "自动标注完成：添加了 {0} 个标注",
        "skipped_invalid_labels": "，跳过 {0} 个无效标注",
        "auto_label_completed_no_valid_labels": "自动标注完成，但未添加任何有效标注",
        "auto_label_failed": "自动标注失败：{0}",
        "enable_magnifier": "启用放大镜",
        "current_zoom": "当前倍率：{0}x",
        "color_legend": "颜色图例",
        "load_custom_classes": "载入自订 classes.txt",
        "to": "到",
        "unknown": "未知",
        "error": "错误",
        "auto_label_all_unlabeled": "自动标注所有未标注图片",
        "label_propagation_activated": "标签传播已启用",
        "label_propagation_disabled": "标签传播已停用",
        "viewed": "已检视",
        "index": "索引",
        "total": "总计",
        "error_current_dir_not_set": "错误：未设定当前目录。",
        "bakuai_label_tool": "BakuAI 标注工具",
        "open_image_folder_to_start": "开启图片资料夹以开始",
        "logo_not_found_using_default": "在 {0} 找不到标志，使用预设。",
        "yoloe_wrapper_not_initialized": "YOLOEWrapper 未初始化，请确保已加载类别文件",
        "batch_auto_label_start": "开始批量自动标注...",
        "batch_auto_label_complete": "批量自动标注完成",
        "select_prompt_images_first": "请先选择提示图片（左侧绿色的图片）",
        "overwrite_labeled_images": "覆盖已标注图片？",
        "overwrite_labeled_images_question": "你要覆盖已经标注的图片吗？",
        "all_images_labeled": "所有图片都已标注，无需自动标注。",
        "auto_label_progress_title": "自动标注进度",
        "auto_label_preparing": "准备自动标注...",
        "auto_label_validating": "验证输入文件...",
        "auto_label_building_vpe": "构建视觉提示编码器...",
        "auto_label_setting_classes": "设置类别并准备预测...",
        "auto_label_predicting": "执行目标图像预测...",
        "auto_label_completed_success": "✅ 自动标注完成！\n成功处理了 {0}/{1} 张图片",
        "auto_label_completed_partial": "⚠️ 自动标注完成\n成功处理了 {0}/{1} 张图片",
        "auto_label_failed_error": "❌ 自动标注失败\n错误：{0}",
        "delete_class": "删除类别",
        "confirm_delete_class_title": "确认删除类别",
        "confirm_delete_class_msg": "你确定要删除类别 '{0}' 吗？\n此操作无法撤销。",
        "delete_related_annotations_title": "删除相关标注",
        "delete_related_annotations_msg": "在当前图片中发现 {0} 个使用类别 '{1}' 的标注。\n你要一起删除这些标注吗？",
        "auto_label_current_image": "自动标注当前图片",
        "auto_label_current_title": "自动标注当前图片",
        "auto_label_current_confirm": "使用当前图片的标注作为提示来自动标注同一张图片？\n这将帮助在当前图片中找到相似的物体。",
        "no_current_image": "没有加载当前图片",
        "current_image_no_annotations": "当前图片没有标注可用作提示",
        "failed_to_build_visuals": "无法从当前标注构建视觉提示",
        "replace_annotations_title": "替换标注",
        "replace_annotations_msg": "你要用新的预测结果替换现有标注吗？\n选择'否'将新预测添加到现有标注中。",
        "auto_label_current_success": "当前图片自动标注完成！\n添加了 {0} 个新标注。",
        "switch_project_title": "切换项目",
        "switch_project_confirm": "当前工作可能会丢失。你确定要切换到新项目吗？",
        "project_loaded": "项目 '{0}' 已加载，包含 {1} 张图片",
        "refresh_data": "刷新数据",
        "refresh_data_tooltip": "刷新项目数据并重新扫描标注文件",
        "project_info": "项目信息",
        "current_project": "当前项目",
        "total_images": "总图片数",
        "labeled_images": "已标注图片",
        "unlabeled_images": "未标注图片",
        "no_labeled_images_found": "在当前项目中没有找到已标注的图片",
        "objects": "个对象",
        "refresh_complete": "刷新完成",
        "refresh_complete_msg": "在当前项目中找到 {0} 张已标注的图片",
    },
    "ja": {
        "open": "開く",
        "save": "保存",
        "next_image": "次の画像",
        "prev_image": "前の画像",
        "delete": "選択したボックスを削除",
        "auto_save": "自動保存",
        "label_propagation": "ラベル伝播",
        "output_format": "出力形式",
        "classes": "クラス",
        "ready": "準備完了",
        "no_classes_file": "このフォルダに classes.txt が見つかりません。\n既存の txt ファイルをクラスファイルとして選択しますか？\nはいを選択するとファイルを選択、いいえで手動入力。",
        "yes": "はい",
        "no": "いいえ",
        "hotkeys_help": "ショートカット一覧",
        "quit": "終了",
        "file_menu": "ファイル(&F)",
        "load_label_file": "ラベルファイルを読み込む (例：.txt)",
        "help_menu": "ヘルプ(&H)",
        "hotkeys_menu": "ショートカット(&K)",
        "about_menu": "BakuAI ASについて(&A)",
        "hotkeys_title": "ショートカット一覧",
        "hotkeys_list": "ショートカットリスト：",
        "next_image_hotkey": "次の画像",
        "prev_image_hotkey": "前の画像",
        "save_hotkey": "注釈を保存",
        "open_hotkey": "フォルダを開く",
        "delete_hotkey": "選択したボックスを削除",
        "quit_hotkey": "終了",
        "label_propagation_hotkey": "ラベルのコピーを切り替え",
        "multi_select_hotkey": "複数選択ボックス",
        "undo_hotkey": "元に戻す (画像ごと)",
        "redo_hotkey": "やり直す (画像ごと)",
        "about_title": "BakuAIについて",
        "version": "バージョン",
        "copyright": "Copyright Reserved",
        "website": "Official Website",
        "software_description": "このソフトウェアは画像ラベリング用で、YOLO/VOC/COCO 形式をサポートしています",
        "debug_info": "デバッグ情報",
        "current_working_dir": "現在の作業ディレクトリ",
        "dist_dir_contents": "Dist ディレクトリの内容",
        "debug_info_end": "デバッグ情報終了",
        "class_save_failed": "クラス保存失敗",
        "failed_to_write_classes": "classes.txt の書き込みに失敗：{0}",
        "save_error": "保存エラー",
        "failed_to_save_yolo": "YOLO アノテーションの保存に失敗：\n{0}",
        "edit_label": "ラベルを編集",
        "enter_new_label": "新しいラベルを入力：",
        "warning": "警告",
        "no_image": "画像が読み込まれていません。先に画像を開いてください。",
        "auto_label_menu": "自動ラベリング(&A)",
        "auto_label_title": "ビジュアルプロンプト自動ラベリング",
        "select_prompt_images": "プロンプト画像を選択",
        "select_target_image": "ターゲット画像を選択",
        "no_prompt_images": "プロンプト画像が選択されていません",
        "no_target_image": "ターゲット画像が選択されていません",
        "auto_label_error": "自動ラベリングに失敗しました",
        "auto_label_success": "自動ラベリングが完了しました",
        "enable_magnifier": "拡大鏡を有効にする",
        "current_zoom": "現在のズーム：{0}x",
        "color_legend": "色の凡例",
        "load_custom_classes": "カスタム classes.txt を読み込む",
        "to": "から",
        "unknown": "不明",
        "error": "エラー",
        "auto_label_all_unlabeled": "すべての未ラベル画像を自動ラベリング",
        "label_propagation_activated": "ラベル伝播が有効",
        "label_propagation_disabled": "ラベル伝播が無効",
        "viewed": "表示済み",
        "index": "インデックス",
        "total": "合計",
        "error_current_dir_not_set": "エラー：現在のディレクトリが設定されていません。",
        "bakuai_label_tool": "BakuFlow",
        "open_image_folder_to_start": "開始するには画像フォルダを開いてください",
        "logo_not_found_using_default": "{0} でロゴが見つかりません、デフォルトを使用します。",
        "yoloe_wrapper_not_initialized": "YOLOEWrapper 未初始化，请确保已加载类别文件",
        "batch_auto_label_start": "開始批量自動標註...",
        "batch_auto_label_complete": "批量自動標註完成",
        "select_prompt_images_first": "請先選擇提示圖片（左側綠色的圖片）",
        "overwrite_labeled_images": "覆蓋已標註圖片？",
        "overwrite_labeled_images_question": "你要覆蓋已經標註的圖片嗎？",
        "all_images_labeled": "所有圖片都已標註，無需自動標註。",
        "auto_label_progress_title": "自動標註進度",
        "auto_label_preparing": "準備自動標註...",
        "auto_label_validating": "驗證輸入文件...",
        "auto_label_building_vpe": "構建視覺提示編碼器...",
        "auto_label_setting_classes": "設置類別並準備預測...",
        "auto_label_predicting": "執行目標圖像預測...",
        "auto_label_completed_success": "✅ 自動標註完成！\n成功處理了 {0}/{1} 張圖片",
        "auto_label_completed_partial": "⚠️ 自動標註完成\n成功處理了 {0}/{1} 張圖片",
        "auto_label_failed_error": "❌ 自動標註失敗\n錯誤：{0}",
        "delete_class": "刪除類別",
        "confirm_delete_class_title": "確認刪除類別",
        "confirm_delete_class_msg": "你確定要刪除類別 '{0}' 嗎？\n此操作無法撤銷。",
        "delete_related_annotations_title": "刪除相關標註",
        "delete_related_annotations_msg": "在當前圖片中發現 {0} 個使用類別 '{1}' 的標註。\n你要一起刪除這些標註嗎？",
        "auto_label_current_image": "自動標註當前圖片",
        "auto_label_current_title": "自動標註當前圖片",
        "auto_label_current_confirm": "使用當前圖片的標註作為提示來自動標註同張圖片？\n這將幫助在當前圖片中找到相似的物體。",
        "no_current_image": "沒有加載當前圖片",
        "current_image_no_annotations": "當前圖片沒有標註可用作提示",
        "failed_to_build_visuals": "無法從當前標註構建視覺提示",
        "replace_annotations_title": "替換標註",
        "replace_annotations_msg": "你要用新的預測結果替換現有標註嗎？\n選擇'否'將新預測添加到現有標註中。",
        "auto_label_current_success": "當前圖片自動標註完成！\n添加了 {0} 個新標註。",
        "switch_project_title": "切換項目",
        "switch_project_confirm": "當前工作可能會丟失。你確定要切換到新項目嗎？",
        "project_loaded": "項目 '{0}' 已加載，包含 {1} 張圖片",
        "refresh_data": "刷新數據",
        "refresh_data_tooltip": "刷新項目數據並重新掃描標註文件",
        "project_info": "項目信息",
        "current_project": "當前項目",
        "total_images": "總圖片數",
        "labeled_images": "已標註圖片",
        "unlabeled_images": "未標註圖片",
        "no_labeled_images_found": "在當前項目中沒有找到已標註的圖片",
        "objects": "個對象",
        "refresh_complete": "刷新完成",
        "refresh_complete_msg": "在當前項目中找到 {0} 張已標註的圖片",
    },
    "it": {
        "open": "Apri",
        "save": "Salva",
        "next_image": "Immagine successiva",
        "prev_image": "Immagine precedente",
        "delete": "Elimina box selezionati",
        "auto_save": "Salvataggio automatico",
        "label_propagation": "Propagazione etichette",
        "output_format": "Formato di output",
        "classes": "Classi",
        "ready": "Pronto",
        "no_classes_file": "Nessun classes.txt trovato in questa cartella.\nVuoi selezionare un file txt esistente come file delle classi?\nSì per selezionare, No per inserire manualmente.",
        "yes": "Sì",
        "no": "No",
        "hotkeys_help": "Scorciatoie da tastiera",
        "quit": "Esci",
        "file_menu": "File(&F)",
        "load_label_file": "Carica file etichette (es. .txt)",
        "help_menu": "Aiuto(&H)",
        "hotkeys_menu": "Scorciatoie(&K)",
        "about_menu": "Informazioni su BakuAI AS(&A)",
        "hotkeys_title": "Scorciatoie da tastiera",
        "hotkeys_list": "Elenco scorciatoie：",
        "next_image_hotkey": "Immagine successiva",
        "prev_image_hotkey": "Immagine precedente",
        "save_hotkey": "Salva annotazioni",
        "open_hotkey": "Apri directory",
        "delete_hotkey": "Elimina box selezionati",
        "quit_hotkey": "Esci",
        "label_propagation_hotkey": "Cambia copia etichette",
        "multi_select_hotkey": "Selezione multipla box",
        "undo_hotkey": "Annulla (per immagine)",
        "redo_hotkey": "Ripeti (per immagine)",
        "about_title": "Informazioni su BakuAI",
        "version": "Versione",
        "copyright": "Tutti i diritti riservati",
        "website": "Sito ufficiale",
        "software_description": "Questo software è utilizzato per l'etichettatura delle immagini, supporta i formati YOLO/VOC/COCO",
        "debug_info": "Informazioni di debug",
        "current_working_dir": "Directory di lavoro corrente",
        "dist_dir_contents": "Contenuto directory Dist",
        "debug_info_end": "Fine informazioni di debug",
        "class_save_failed": "Salvataggio classe fallito",
        "failed_to_write_classes": "Impossibile scrivere classes.txt: {0}",
        "save_error": "Errore di salvataggio",
        "failed_to_save_yolo": "Impossibile salvare le annotazioni YOLO:\n{0}",
        "edit_label": "Modifica etichetta",
        "enter_new_label": "Inserisci nuova etichetta:",
        "data_aug_menu": "Aumento Dati(&D)",
        "data_aug_title": "Impostazioni Batch di Data Augmentation",
        "saturation": "Saturazione",
        "contrast": "Contrasto",
        "brightness": "Luminosità",
        "rotation": "Rotazione (gradi)",
        "flip_ud": "Ribalta Su-Giù",
        "flip_lr": "Ribalta Sinistra-Destra",
        "apply": "Applica",
        "cancel": "Annulla",
        "reset": "Resetta",
        "preview": "Anteprima",
        "aug_per_image": "Augmentazioni per immagine",
        "output_folder": "Cartella di output",
        "select_folder": "Seleziona cartella",
        "processing": "Elaborazione...",
        "aug_complete": "Aumento completato",
        "aug_progress": "Elaborazione immagine {0}/{1}",
        "aug_success": "{0} immagini aumentate con successo",
        "aug_error": "Errore durante il processo di aumento",
        "preserve_original": "Conserva file originali",
        "aug_settings": "Impostazioni di aumento",
        "random_rotation": "Intervallo rotazione casuale",
        "random_brightness": "Intervallo luminosità casuale",
        "random_contrast": "Intervallo contrasto casuale",
        "random_saturation": "Intervallo saturazione casuale",
        "flip_options": "Opzioni di ribaltamento",
        "warning": "Avviso",
        "no_image": "Nessuna immagine caricata, aprire prima un'immagine.",
        "auto_label_menu": "Etichettatura Automatica(&A)",
        "auto_label_title": "Etichettatura Automatica con Prompt Visivo",
        "select_prompt_images": "Seleziona immagini prompt",
        "select_target_image": "Seleziona immagine target",
        "no_prompt_images": "Nessuna immagine prompt selezionata",
        "no_target_image": "Nessuna immagine target selezionata",
        "auto_label_error": "Etichettatura automatica fallita",
        "auto_label_success": "Etichettatura automatica completata",
        "error_no_class_list": "Errore: elenco classi non trovato nella finestra principale (label_hist)",
        "error_target_image_not_exist": "Errore: immagine target non esiste: {0}",
        "error_prompt_image_not_exist": "Errore: immagine prompt non esiste: {0}",
        "processing_vp_auto_label": "Elaborazione etichettatura automatica con prompt visivo...",
        "converting_annotations": "Conversione annotazioni...",
        "executing_prediction": "Esecuzione predizione...",
        "warning_unknown_class_id": "Avviso: ID classe sconosciuto {0}",
        "error_adding_bbox": "Fehler beim Hinzufügen der Bounding Box: {0}",
        "error_loading_annotation": "Laden der Annotationsdatei fehlgeschlagen: {0}",
        "info_using_pascal_voc_reader": "Info: utilizzo lettore Pascal VOC",
        "info_using_yolo_reader": "Info: utilizzo lettore YOLO",
        "warning_no_compatible_reader": "Avviso: nessun lettore annotazioni compatibile trovato",
        "warning_no_annotation_file": "Avviso: file annotazione non trovato: {0}",
        "warning_no_valid_annotations": "Avviso: nessuna annotazione valida trovata: {0}",
        "warning_unknown_class": "Avviso: classe sconosciuta {0}",
        "warning_invalid_bbox_coords": "Avviso: coordinate bounding box non valide [{0}, {1}, {2}, {3}]",
        "warning_cannot_get_bbox_coords": "Avviso: impossibile ottenere coordinate bounding box, annotazione saltata",
        "error_processing_annotation": "Errore nell'elaborazione file annotazione {0}: {1}",
        "auto_label_completed": "Etichettatura automatica completata: aggiunte {0} annotazioni",
        "skipped_invalid_labels": ", saltate {0} annotazioni non valide",
        "auto_label_completed_no_valid_labels": "Etichettatura automatica completata, ma nessuna annotazione valida aggiunta",
        "auto_label_failed": "Etichettatura automatica fallita: {0}",
        "enable_magnifier": "Abilita lente d'ingrandimento",
        "current_zoom": "Zoom corrente: {0}x",
        "color_legend": "Legenda colori",
        "load_custom_classes": "Carica classes.txt personalizzato",
        "to": "a",
        "unknown": "sconosciuto",
        "error": "Errore",
        "auto_label_all_unlabeled": "Etichetta automaticamente tutte le immagini non etichettate",
        "label_propagation_activated": "Propagazione etichetta attivata",
        "label_propagation_disabled": "Propagazione etichetta disattivata",
        "viewed": "Visualizzato",
        "index": "Indice",
        "total": "Totale",
        "error_current_dir_not_set": "Errore: directory corrente non impostata.",
        "bakuai_label_tool": "Strumento di Etichettatura BakuAI",
        "open_image_folder_to_start": "Apri cartella immagini per iniziare",
        "logo_not_found_using_default": "Logo non trovato in {0}, utilizzo predefinito.",
        "yoloe_wrapper_not_initialized": "YOLOEWrapper 未初始化，请确保已加载类别文件",
        "batch_auto_label_start": "開始批量自動標註...",
        "batch_auto_label_complete": "批量自動標註完成",
        "select_prompt_images_first": "請先選擇提示圖片（左側綠色的圖片）",
        "overwrite_labeled_images": "覆蓋已標註圖片？",
        "overwrite_labeled_images_question": "你要覆蓋已經標註的圖片嗎？",
        "all_images_labeled": "所有圖片都已標註，無需自動標註。",
        "auto_label_progress_title": "自動標註進度",
        "auto_label_preparing": "準備自動標註...",
        "auto_label_validating": "驗證輸入文件...",
        "auto_label_building_vpe": "構建視覺提示編碼器...",
        "auto_label_setting_classes": "設置類別並準備預測...",
        "auto_label_predicting": "執行目標圖像預測...",
        "auto_label_completed_success": "✅ 自動標註完成！\n成功處理了 {0}/{1} 張圖片",
        "auto_label_completed_partial": "⚠️ 自動標註完成\n成功處理了 {0}/{1} 張圖片",
        "auto_label_failed_error": "❌ 自動標註失敗\n錯誤：{0}",
        "delete_class": "刪除類別",
        "confirm_delete_class_title": "確認刪除類別",
        "confirm_delete_class_msg": "你確定要刪除類別 '{0}' 嗎？\n此操作無法撤銷。",
        "delete_related_annotations_title": "刪除相關標註",
        "delete_related_annotations_msg": "在當前圖片中發現 {0} 個使用類別 '{1}' 的標註。\n你要一起刪除這些標註嗎？",
        "auto_label_current_image": "自動標註當前圖片",
        "auto_label_current_title": "自動標註當前圖片",
        "auto_label_current_confirm": "使用當前圖片的標註作為提示來自動標註同張圖片？\n這將幫助在當前圖片中找到相似的物體。",
        "no_current_image": "沒有加載當前圖片",
        "current_image_no_annotations": "當前圖片沒有標註可用作提示",
        "failed_to_build_visuals": "無法從當前標註構建視覺提示",
        "replace_annotations_title": "替換標註",
        "replace_annotations_msg": "你要用新的預測結果替換現有標註嗎？\n選擇'否'將新預測添加到現有標註中。",
        "auto_label_current_success": "當前圖片自動標註完成！\n添加了 {0} 個新標註。",
        "switch_project_title": "切換項目",
        "switch_project_confirm": "當前工作可能會丟失。你確定要切換到新項目嗎？",
        "project_loaded": "項目 '{0}' 已加載，包含 {1} 張圖片",
        "refresh_data": "刷新數據",
        "refresh_data_tooltip": "刷新項目數據並重新掃描標註文件",
        "project_info": "項目信息",
        "current_project": "當前項目",
        "total_images": "總圖片數",
        "labeled_images": "已標註圖片",
        "unlabeled_images": "未標註圖片",
        "no_labeled_images_found": "在當前項目中沒有找到已標註的圖片",
        "objects": "個對象",
        "refresh_complete": "刷新完成",
        "refresh_complete_msg": "在當前項目中找到 {0} 張已標註的圖片",
    },
    "de": {
        "open": "Öffnen",
        "save": "Speichern",
        "next_image": "Nächstes Bild",
        "prev_image": "Vorheriges Bild",
        "delete": "Ausgewählte Box(en) löschen",
        "auto_save": "Automatisch speichern",
        "label_propagation": "Labels kopieren",
        "output_format": "Ausgabeformat",
        "classes": "Klassen",
        "ready": "Bereit",
        "no_classes_file": "Keine classes.txt in diesem Ordner gefunden.\nMöchten Sie eine vorhandene txt-Datei als Klassen-Datei auswählen?\nJa zum Auswählen, Nein zum manuellen Eingeben.",
        "yes": "Ja",
        "no": "Nein",
        "hotkeys_help": "Tastenkombinationen",
        "quit": "Beenden",
        "file_menu": "Datei(&F)",
        "load_label_file": "Label-Datei laden (z.B. .txt)",
        "help_menu": "Hilfe(&H)",
        "hotkeys_menu": "Tastenkombinationen(&K)",
        "about_menu": "Über BakuAI AS(&A)",
        "hotkeys_title": "Tastenkombinationen",
        "hotkeys_list": "Tastenkombinationen Liste：",
        "next_image_hotkey": "Nächstes Bild",
        "prev_image_hotkey": "Vorheriges Bild",
        "save_hotkey": "Anmerkungen speichern",
        "open_hotkey": "Verzeichnis öffnen",
        "delete_hotkey": "Ausgewählte Box(en) löschen",
        "quit_hotkey": "Beenden",
        "label_propagation_hotkey": "Labels kopieren umschalten",
        "multi_select_hotkey": "Mehrfachauswahl Boxen",
        "undo_hotkey": "Rückgängig (pro Bild)",
        "redo_hotkey": "Wiederholen (pro Bild)",
        "about_title": "Über BakuAI",
        "version": "Version",
        "copyright": "Alle Rechte vorbehalten",
        "website": "Offizielle Website",
        "software_description": "Diese Software wird für die Bildbeschriftung verwendet und unterstützt YOLO/VOC/COCO-Formate",
        "debug_info": "Debug-Informationen",
        "current_working_dir": "Aktuelles Arbeitsverzeichnis",
        "dist_dir_contents": "Dist-Verzeichnisinhalt",
        "debug_info_end": "Debug-Informationen Ende",
        "class_save_failed": "Klassenspeicherung fehlgeschlagen",
        "failed_to_write_classes": "Konnte classes.txt nicht schreiben: {0}",
        "save_error": "Speicherfehler",
        "failed_to_save_yolo": "YOLO-Annotationen konnten nicht gespeichert werden:\n{0}",
        "edit_label": "Beschriftung bearbeiten",
        "enter_new_label": "Neue Beschriftung eingeben:",
        "data_aug_menu": "Datenaugmentation(&D)",
        "data_aug_title": "Batch-Datenaugmentation",
        "saturation": "Sättigung",
        "contrast": "Kontrast",
        "brightness": "Helligkeit",
        "rotation": "Rotation (Grad)",
        "flip_ud": "Vertikal spiegeln",
        "flip_lr": "Horizontal spiegeln",
        "apply": "Anwenden",
        "cancel": "Abbrechen",
        "reset": "Zurücksetzen",
        "preview": "Vorschau",
        "aug_per_image": "Augmentierungen pro Bild",
        "output_folder": "Ausgabeordner",
        "select_folder": "Ordner auswählen",
        "processing": "Verarbeitung...",
        "aug_complete": "Augmentation abgeschlossen",
        "aug_progress": "Verarbeite {0}/{1} Bilder",
        "aug_success": "{0} Bilder erfolgreich augmentiert",
        "aug_error": "Fehler bei der Augmentation",
        "preserve_original": "Originaldateien behalten",
        "aug_settings": "Augmentierungseinstellungen",
        "random_rotation": "Zufälliger Rotationsbereich",
        "random_brightness": "Zufälliger Helligkeitsbereich",
        "random_contrast": "Zufälliger Kontrastbereich",
        "random_saturation": "Zufälliger Sättigungsbereich",
        "flip_options": "Spiegelungsoptionen",
        "warning": "Warnung",
        "no_image": "Kein Bild geladen. Bitte zuerst ein Bild öffnen.",
        "auto_label_menu": "Automatische Beschriftung(&A)",
        "auto_label_title": "Visuelle Prompt Automatische Beschriftung",
        "select_prompt_images": "Prompt-Bilder auswählen",
        "select_target_image": "Zielbild auswählen",
        "no_prompt_images": "Keine Prompt-Bilder ausgewählt",
        "no_target_image": "Kein Zielbild ausgewählt",
        "auto_label_error": "Automatische Beschriftung fehlgeschlagen",
        "auto_label_success": "Automatische Beschriftung erfolgreich abgeschlossen",
        "error_no_class_list": "Fehler: Klassenliste nicht im Hauptfenster gefunden (label_hist)",
        "error_target_image_not_exist": "Fehler: Zielbild existiert nicht: {0}",
        "error_prompt_image_not_exist": "Fehler: Prompt-Bild existiert nicht: {0}",
        "processing_vp_auto_label": "Verarbeitung der visuellen Prompt automatischen Beschriftung...",
        "converting_annotations": "Konvertierung der Annotationen...",
        "executing_prediction": "Ausführung der Vorhersage...",
        "warning_unknown_class_id": "Warnung: Unbekannte Klassen-ID {0}",
        "error_adding_bbox": "Fehler beim Hinzufügen der Bounding Box: {0}",
        "error_loading_annotation": "Laden der Annotationsdatei fehlgeschlagen: {0}",
        "info_using_pascal_voc_reader": "Info: Verwende Pascal VOC Reader",
        "info_using_yolo_reader": "Info: Verwende YOLO Reader",
        "warning_no_compatible_reader": "Warnung: Kein kompatibler Annotations-Reader gefunden",
        "warning_no_annotation_file": "Warnung: Annotationsdatei nicht gefunden: {0}",
        "warning_no_valid_annotations": "Warnung: Keine gültigen Annotationen gefunden: {0}",
        "warning_unknown_class": "Warnung: Unbekannte Klasse {0}",
        "warning_invalid_bbox_coords": "Warnung: Ungültige Bounding Box Koordinaten [{0}, {1}, {2}, {3}]",
        "warning_cannot_get_bbox_coords": "Warnung: Kann Bounding Box Koordinaten nicht abrufen, Annotation übersprungen",
        "error_processing_annotation": "Fehler bei der Verarbeitung der Annotationsdatei {0}: {1}",
        "auto_label_completed": "Automatische Beschriftung abgeschlossen: aggiunte {0} annotazioni",
        "skipped_invalid_labels": ", saltate {0} annotazioni non valide",
        "auto_label_completed_no_valid_labels": "Automatische Beschriftung abgeschlossen, aber keine gültigen Annotationen hinzugefügt",
        "auto_label_failed": "Automatische Beschriftung fehlgeschlagen: {0}",
        "enable_magnifier": "Lupe aktivieren",
        "current_zoom": "Aktueller Zoom: {0}x",
        "color_legend": "Farblegende",
        "load_custom_classes": "Benutzerdefinierte classes.txt laden",
        "to": "bis",
        "unknown": "unbekannt",
        "error": "Fehler",
        "auto_label_all_unlabeled": "Alle unbeschrifteten Bilder automatisch beschriften",
        "label_propagation_activated": "Labels kopie aktiviert",
        "label_propagation_disabled": "Labels kopie deaktiviert",
        "viewed": "Angesehen",
        "index": "Index",
        "total": "Gesamt",
        "error_current_dir_not_set": "Fehler: Aktuelles Verzeichnis nicht gesetzt.",
        "bakuai_label_tool": "BakuAI Beschriftungstool",
        "open_image_folder_to_start": "Bildordner öffnen um zu beginnen",
        "logo_not_found_using_default": "Logo nicht gefunden unter {0}, verwende Standard.",
        "yoloe_wrapper_not_initialized": "YOLOEWrapper 未初始化，请确保已加载类别文件",
        "batch_auto_label_start": "開始批量自動標註...",
        "batch_auto_label_complete": "批量自動標註完成",
        "select_prompt_images_first": "請先選擇提示圖片（左側綠色的圖片）",
        "overwrite_labeled_images": "覆蓋已標註圖片？",
        "overwrite_labeled_images_question": "你要覆蓋已經標註的圖片嗎？",
        "all_images_labeled": "所有圖片都已標註，無需自動標註。",
        "auto_label_progress_title": "自動標註進度",
        "auto_label_preparing": "準備自動標註...",
        "auto_label_validating": "驗證輸入文件...",
        "auto_label_building_vpe": "構建視覺提示編碼器...",
        "auto_label_setting_classes": "設置類別並準備預測...",
        "auto_label_predicting": "執行目標圖像預測...",
        "auto_label_completed_success": "✅ 自動標註完成！\n成功處理了 {0}/{1} 張圖片",
        "auto_label_completed_partial": "⚠️ 自動標註完成\n成功處理了 {0}/{1} 張圖片",
        "auto_label_failed_error": "❌ 自動標註失敗\n錯誤：{0}",
        "delete_class": "刪除類別",
        "confirm_delete_class_title": "確認刪除類別",
        "confirm_delete_class_msg": "你確定要刪除類別 '{0}' 嗎？\n此操作無法撤銷。",
        "delete_related_annotations_title": "刪除相關標註",
        "delete_related_annotations_msg": "在當前圖片中發現 {0} 個使用類別 '{1}' 的標註。\n你要一起刪除這些標註嗎？",
        "auto_label_current_image": "自動標註當前圖片",
        "auto_label_current_title": "自動標註當前圖片",
        "auto_label_current_confirm": "使用當前圖片的標註作為提示來自動標註同張圖片？\n這將幫助在當前圖片中找到相似的物體。",
        "no_current_image": "沒有加載當前圖片",
        "current_image_no_annotations": "當前圖片沒有標註可用作提示",
        "failed_to_build_visuals": "無法從當前標註構建視覺提示",
        "replace_annotations_title": "替換標註",
        "replace_annotations_msg": "你要用新的預測結果替換現有標註嗎？\n選擇'否'將新預測添加到現有標註中。",
        "auto_label_current_success": "當前圖片自動標註完成！\n添加了 {0} 個新標註。",
        "switch_project_title": "切換項目",
        "switch_project_confirm": "當前工作可能會丟失。你確定要切換到新項目嗎？",
        "project_loaded": "項目 '{0}' 已加載，包含 {1} 張圖片",
        "refresh_data": "刷新數據",
        "refresh_data_tooltip": "刷新項目數據並重新掃描標註文件",
        "project_info": "項目信息",
        "current_project": "當前項目",
        "total_images": "總圖片數",
        "labeled_images": "已標註圖片",
        "unlabeled_images": "未標註圖片",
        "no_labeled_images_found": "在當前項目中沒有找到已標註的圖片",
        "objects": "個對象",
        "refresh_complete": "刷新完成",
        "refresh_complete_msg": "在當前項目中找到 {0} 張已標註的圖片",
    },
    "no": {
        "open": "Åpne",
        "save": "Lagre",
        "next_image": "Neste bilde",
        "prev_image": "Forrige bilde",
        "delete": "Slett valgte bokser",
        "auto_save": "Auto-lagring",
        "label_propagation": "Kopier etiketter",
        "output_format": "Utdataformat",
        "classes": "Klasser",
        "ready": "Klar",
        "no_classes_file": "Fant ikke classes.txt i denne mappen.\nVil du velge en eksisterende txt-fil som klassefil?\nJa for å velge, Nei for å skrive inn manuelt.",
        "yes": "Ja",
        "no": "Nei",
        "hotkeys_help": "Hurtigtaster",
        "quit": "Avslutt",
        "file_menu": "Fil(&F)",
        "load_label_file": "Last inn merkelappfil (f.eks. .txt)",
        "help_menu": "Hjelp(&H)",
        "hotkeys_menu": "Hurtigtaster(&K)",
        "about_menu": "Om BakuAI AS(&A)",
        "hotkeys_title": "Hurtigtaster",
        "hotkeys_list": "Hurtigtastliste：",
        "next_image_hotkey": "Neste bilde",
        "prev_image_hotkey": "Forrige bilde",
        "save_hotkey": "Lagre merknader",
        "open_hotkey": "Åpne mappe",
        "delete_hotkey": "Slett valgte bokser",
        "quit_hotkey": "Avslutt",
        "label_propagation_hotkey": "Bytt kopiering av etiketter",
        "multi_select_hotkey": "Flervalg av bokser",
        "undo_hotkey": "Angre (per bilde)",
        "redo_hotkey": "Gjør om (per bilde)",
        "about_title": "Om BakuAI",
        "version": "Versjon",
        "copyright": "Alle rettigheter reservert",
        "website": "Offisiell nettside",
        "software_description": "Dette programvaren brukes til bildemerkering, støtter YOLO/VOC/COCO-formater",
        "debug_info": "Feilsøkingsinformasjon",
        "current_working_dir": "Nåværende arbeidsmappe",
        "dist_dir_contents": "Dist-mappeinnhold",
        "debug_info_end": "Feilsøkingsinformasjon slutt",
        "class_save_failed": "Klasselagring mislyktes",
        "failed_to_write_classes": "Kunne ikke skrive classes.txt: {0}",
        "save_error": "Lagringsfeil",
        "failed_to_save_yolo": "Kunne ikke lagre YOLO-annotasjoner:\n{0}",
        "edit_label": "Rediger etikett",
        "enter_new_label": "Skriv inn ny etikett:",
        "data_aug_menu": "Dataforsterkning(&D)",
        "data_aug_title": "Batch Dataforsterkning",
        "saturation": "Metning",
        "contrast": "Kontrast",
        "brightness": "Lysstyrke",
        "rotation": "Rotasjon (grader)",
        "flip_ud": "Vend opp-ned",
        "flip_lr": "Vend venstre-høyre",
        "apply": "Bruk",
        "cancel": "Avbryt",
        "reset": "Tilbakestill",
        "preview": "Forhåndsvisning",
        "aug_per_image": "Forsterkninger per bilde",
        "output_folder": "Utdata-mappe",
        "select_folder": "Velg mappe",
        "processing": "Behandler...",
        "aug_complete": "Forsterkning fullført",
        "aug_progress": "Behandler {0}/{1} bilder",
        "aug_success": "{0} bilder forsterket",
        "aug_error": "Feil under forsterkning",
        "preserve_original": "Behold originalfiler",
        "aug_settings": "Forsterkningsinnstillinger",
        "random_rotation": "Tilfeldig rotasjonsområde",
        "random_brightness": "Tilfeldig lysstyrkeområde",
        "random_contrast": "Tilfeldig kontrastområde",
        "random_saturation": "Tilfeldig metningsområde",
        "flip_options": "Vendingsvalg",
        "warning": "Advarsel",
        "no_image": "Ingen bilde lastet. Vennligst åpne et bilde først.",
        "auto_label_menu": "Automatisk merking(&A)",
        "auto_label_title": "Visuell prompt automatisk merking",
        "select_prompt_images": "Velg prompt-bilder",
        "select_target_image": "Velg målbilde",
        "no_prompt_images": "Ingen prompt-bilder valgt",
        "no_target_image": "Ingen målbilde valgt",
        "auto_label_error": "Automatisk merking mislyktes",
        "auto_label_success": "Automatisk merking fullført",
        "error_no_class_list": "Feil: klasseliste ikke funnet i hovedvinduet (label_hist)",
        "error_target_image_not_exist": "Feil: målbilde eksisterer ikke: {0}",
        "error_prompt_image_not_exist": "Feil: prompt-bilde eksisterer ikke: {0}",
        "processing_vp_auto_label": "Behandler visuell prompt automatisk merking...",
        "converting_annotations": "Konverterer annotasjoner...",
        "executing_prediction": "Utfører prediksjon...",
        "warning_unknown_class_id": "Advarsel: ukjent klasse-ID {0}",
        "error_adding_bbox": "Feil ved tillegging av bounding box: {0}",
        "error_loading_annotation": "Lasting av annotasjonsfil mislyktes: {0}",
        "info_using_pascal_voc_reader": "Info: bruker Pascal VOC leser",
        "info_using_yolo_reader": "Info: bruker YOLO leser",
        "warning_no_compatible_reader": "Advarsel: ingen kompatibel annotasjonsleser funnet",
        "warning_no_annotation_file": "Advarsel: annotasjonsfil ikke funnet: {0}",
        "warning_no_valid_annotations": "Advarsel: ingen gyldige annotasjoner funnet: {0}",
        "warning_unknown_class": "Advarsel: ukjent klasse {0}",
        "warning_invalid_bbox_coords": "Advarsel: ugyldige bounding box koordinater [{0}, {1}, {2}, {3}]",
        "warning_cannot_get_bbox_coords": "Advarsel: impossibile ottenere coordinate bounding box, annotazione saltata",
        "error_processing_annotation": "Feil ved behandling av annotasjonsfil {0}: {1}",
        "auto_label_completed": "Automatisk merking fullført: lagt til {0} annotasjoner",
        "skipped_invalid_labels": ", saltate {0} annotasjoner invælide",
        "auto_label_completed_no_valid_labels": "Automatisk merking fullført, men ingen gyldige annotasjoner lagt til",
        "auto_label_failed": "Automatisk merking mislyktes: {0}",
        "enable_magnifier": "Aktiver forstørrelsesglass",
        "current_zoom": "Nåværende zoom: {0}x",
        "color_legend": "Fargelegende",
        "load_custom_classes": "Last inn tilpasset classes.txt",
        "to": "til",
        "unknown": "ukjent",
        "error": "Feil",
        "auto_label_all_unlabeled": "Automatisk merk alle umerkede bilder",
        "label_propagation_activated": "Labels kopie aktiviert",
        "label_propagation_disabled": "Labels kopie deaktiviert",
        "viewed": "Sett",
        "index": "Indeks",
        "total": "Totalt",
        "error_current_dir_not_set": "Feil: nåværende katalog ikke satt.",
        "bakuai_label_tool": "BakuAI merkingsverktøy",
        "open_image_folder_to_start": "Åpne bildemappe for å starte",
        "logo_not_found_using_default": "Logo ikke funnet på {0}, bruker standard.",
        "yoloe_wrapper_not_initialized": "YOLOEWrapper 未初始化，请确保已加载类别文件",
        "batch_auto_label_start": "開始批量自動標註...",
        "batch_auto_label_complete": "批量自動標註完成",
        "select_prompt_images_first": "請先選擇提示圖片（左側綠色的圖片）",
        "overwrite_labeled_images": "覆蓋已標註圖片？",
        "overwrite_labeled_images_question": "你要覆蓋已經標註的圖片嗎？",
        "all_images_labeled": "所有圖片都已標註，無需自動標註。",
        "auto_label_progress_title": "自動標註進度",
        "auto_label_preparing": "準備自動標註...",
        "auto_label_validating": "驗證輸入文件...",
        "auto_label_building_vpe": "構建視覺提示編碼器...",
        "auto_label_setting_classes": "設置類別並準備預測...",
        "auto_label_predicting": "執行目標圖像預測...",
        "auto_label_completed_success": "✅ 自動標註完成！\n成功處理了 {0}/{1} 張圖片",
        "auto_label_completed_partial": "⚠️ 自動標註完成\n成功處理了 {0}/{1} 張圖片",
        "auto_label_failed_error": "❌ 自動標註失敗\n錯誤：{0}",
        "delete_class": "刪除類別",
        "confirm_delete_class_title": "確認刪除類別",
        "confirm_delete_class_msg": "你確定要刪除類別 '{0}' 嗎？\n此操作無法撤銷。",
        "delete_related_annotations_title": "刪除相關標註",
        "delete_related_annotations_msg": "在當前圖片中發現 {0} 個使用類別 '{1}' 的標註。\n你要一起刪除這些標註嗎？",
        "auto_label_current_image": "自動標註當前圖片",
        "auto_label_current_title": "自動標註當前圖片",
        "auto_label_current_confirm": "使用當前圖片的標註作為提示來自動標註同張圖片？\n這將幫助在當前圖片中找到相似的物體。",
        "no_current_image": "沒有加載當前圖片",
        "current_image_no_annotations": "當前圖片沒有標註可用作提示",
        "failed_to_build_visuals": "無法從當前標註構建視覺提示",
        "replace_annotations_title": "替換標註",
        "replace_annotations_msg": "你要用新的預測結果替換現有標註嗎？\n選擇'否'將新預測添加到現有標註中。",
        "auto_label_current_success": "當前圖片自動標註完成！\n添加了 {0} 個新標註。",
        "switch_project_title": "切換項目",
        "switch_project_confirm": "當前工作可能會丟失。你確定要切換到新項目嗎？",
        "project_loaded": "項目 '{0}' 已加載，包含 {1} 張圖片",
        "refresh_data": "刷新數據",
        "refresh_data_tooltip": "刷新項目數據並重新掃描標註文件",
        "project_info": "項目信息",
        "current_project": "當前項目",
        "total_images": "總圖片數",
        "labeled_images": "已標註圖片",
        "unlabeled_images": "未標註圖片",
        "no_labeled_images_found": "在當前項目中沒有找到已標註的圖片",
        "objects": "個對象",
        "refresh_complete": "刷新完成",
        "refresh_complete_msg": "在當前項目中找到 {0} 張已標註的圖片",
    },
    "es": {
        "open": "Abrir",
        "save": "Guardar",
        "next_image": "Siguiente imagen",
        "prev_image": "Imagen anterior",
        "delete": "Eliminar cajas seleccionadas",
        "auto_save": "Guardado automático",
        "label_propagation": "Propagación de etiquetas",
        "output_format": "Formato de salida",
        "classes": "Clases",
        "ready": "Listo",
        "no_classes_file": "No se encontró classes.txt en esta carpeta.\n¿Desea seleccionar un archivo txt existente como archivo de clases?\nSí para seleccionar, No para ingresar manualmente.",
        "yes": "Sí",
        "no": "No",
        "hotkeys_help": "Ayuda de atajos",
        "quit": "Salir",
        "file_menu": "Archivo(&F)",
        "load_label_file": "Cargar archivo de etiquetas (ej. .txt)",
        "help_menu": "Ayuda(&H)",
        "hotkeys_menu": "Atajos(&K)",
        "about_menu": "Acerca de BakuAI AS(&A)",
        "hotkeys_title": "Ayuda de atajos",
        "hotkeys_list": "Lista de atajos：",
        "next_image_hotkey": "Siguiente imagen",
        "prev_image_hotkey": "Imagen anterior",
        "save_hotkey": "Guardar anotaciones",
        "open_hotkey": "Abrir directorio",
        "delete_hotkey": "Eliminar cajas seleccionadas",
        "quit_hotkey": "Salir",
        "label_propagation_hotkey": "Cambiar copia de etiquetas",
        "multi_select_hotkey": "Selección múltiple de cajas",
        "undo_hotkey": "Deshacer (por imagen)",
        "redo_hotkey": "Rehacer (por imagen)",
        "about_title": "Acerca de BakuAI",
        "version": "Versión",
        "copyright": "Todos los derechos reservados",
        "website": "Sitio web oficial",
        "software_description": "Este software se utiliza para el etiquetado de imágenes, compatible con formatos YOLO/VOC/COCO",
        "debug_info": "Información de depuración",
        "current_working_dir": "Directorio de trabajo actual",
        "dist_dir_contents": "Contenido del directorio Dist",
        "debug_info_end": "Fin de información de depuración",
        "class_save_failed": "Error al guardar clase",
        "failed_to_write_classes": "No se pudo escribir classes.txt: {0}",
        "save_error": "Error de guardado",
        "failed_to_save_yolo": "Error al guardar anotaciones YOLO:\n{0}",
        "edit_label": "Editar etiqueta",
        "enter_new_label": "Ingrese nueva etiqueta:",
        "data_aug_menu": "Aumento de Datos(&D)",
        "data_aug_title": "Ajustes de Aumento por Lote",
        "saturation": "Saturación",
        "contrast": "Contraste",
        "brightness": "Brillo",
        "rotation": "Rotación (grados)",
        "flip_ud": "Voltear Arriba-Abajo",
        "flip_lr": "Voltear Izquierda-Derecha",
        "apply": "Aplicar",
        "cancel": "Cancelar",
        "reset": "Restablecer",
        "preview": "Vista previa",
        "aug_per_image": "Aumentos por imagen",
        "output_folder": "Carpeta de salida",
        "select_folder": "Seleccionar carpeta",
        "processing": "Procesando...",
        "aug_complete": "Aumento completado",
        "aug_progress": "Procesando {0}/{1} imágenes",
        "aug_success": "{0} imágenes aumentadas correctamente",
        "aug_error": "Error durante el aumento",
        "preserve_original": "Conservar archivos originales",
        "aug_settings": "Configuración de aumento",
        "random_rotation": "Rango de rotación aleatoria",
        "random_brightness": "Rango de luminosité aléatoire",
        "random_contrast": "Rango de contraste aléatoire",
        "random_saturation": "Rango de saturación aleatoria",
        "flip_options": "Opciones de volteo",
        "warning": "Avertissement",
        "no_image": "Aucune image chargée. Veuillez d'abord ouvrir une image.",
        "auto_label_menu": "Étiquetage Automatique(&A)",
        "auto_label_title": "Étiquetage Automatique avec Prompt Visuel",
        "select_prompt_images": "Sélectionner les images prompt",
        "select_target_image": "Sélectionner l'image cible",
        "no_prompt_images": "Aucune image prompt sélectionnée",
        "no_target_image": "Aucune image cible sélectionnée",
        "auto_label_error": "Étiquetage automatique échoué",
        "auto_label_success": "Étiquetage automatique terminé avec succès",
        "error_no_class_list": "Erreur : liste de classes non trouvée dans la fenêtre principale (label_hist)",
        "error_target_image_not_exist": "Erreur : l'image cible n'existe pas : {0}",
        "error_prompt_image_not_exist": "Erreur : l'image prompt n'existe pas : {0}",
        "processing_vp_auto_label": "Traitement de l'étiquetage automatique avec prompt visuel...",
        "converting_annotations": "Conversion des annotations...",
        "executing_prediction": "Exécution de la prédiction...",
        "warning_unknown_class_id": "Avertissement : ID de classe inconnu {0}",
        "error_adding_bbox": "Erreur lors de l'ajout de la boîte englobante : {0}",
        "error_loading_annotation": "Échec du chargement du fichier d'annotation : {0}",
        "info_using_pascal_voc_reader": "Info : utilisation du lecteur Pascal VOC",
        "info_using_yolo_reader": "Info : utilisation du lecteur YOLO",
        "warning_no_compatible_reader": "Avertissement : aucun lecteur d'annotations compatible trouvé",
        "warning_no_annotation_file": "Avertissement : fichier d'annotation non trouvé : {0}",
        "warning_no_valid_annotations": "Avertissement : aucune annotation valide trouvée : {0}",
        "warning_unknown_class": "Avertissement : classe inconnue {0}",
        "warning_invalid_bbox_coords": "Avertissement : coordonnées de boîte englobante invalides [{0}, {1}, {2}, {3}]",
        "warning_cannot_get_bbox_coords": "Avertissement : impossible d'obtenir les coordonnées de la boîte englobante, annotation ignorée",
        "error_processing_annotation": "Erreur lors du traitement du fichier d'annotation {0} : {1}",
        "auto_label_completed": "Étiquetage automatique terminé : {0} annotations ajoutées",
        "skipped_invalid_labels": ", {0} annotations invalides ignorées",
        "auto_label_completed_no_valid_labels": "Étiquetage automatique terminé, mais aucune annotation valide ajoutée",
        "auto_label_failed": "Étiquetage automatique échoué : {0}",
        "enable_magnifier": "Activer la loupe",
        "current_zoom": "Zoom actuel : {0}x",
        "color_legend": "Légende des couleurs",
        "load_custom_classes": "Charger classes.txt personnalisé",
        "to": "à",
        "unknown": "inconnu",
        "error": "Erreur",
        "auto_label_all_unlabeled": "Étiqueter automatiquement toutes les images non étiquetées",
        "label_propagation_activated": "Propagación de etiquetas activada",
        "label_propagation_disabled": "Propagación de etiquetas desactivada",
        "viewed": "Vu",
        "index": "Index",
        "total": "Total",
        "error_current_dir_not_set": "Erreur : répertoire actuel non défini.",
        "bakuai_label_tool": "Outil d'Étiquetage BakuAI",
        "open_image_folder_to_start": "Aprire le dossier d'images pour commencer",
        "logo_not_found_using_default": "Logo non trouvé à {0}, utilisation par défaut.",
        "yoloe_wrapper_not_initialized": "YOLOEWrapper 未初始化，请确保已加载类别文件",
        "batch_auto_label_start": "開始批量自動標註...",
        "batch_auto_label_complete": "批量自動標註完成",
        "select_prompt_images_first": "請先選擇提示圖片（左側綠色的圖片）",
        "overwrite_labeled_images": "覆蓋已標註圖片？",
        "overwrite_labeled_images_question": "你要覆蓋已經標註的圖片嗎？",
        "all_images_labeled": "所有圖片都已標註，無需自動標註。",
        "auto_label_progress_title": "自動標註進度",
        "auto_label_preparing": "準備自動標註...",
        "auto_label_validating": "驗證輸入文件...",
        "auto_label_building_vpe": "構建視覺提示編碼器...",
        "auto_label_setting_classes": "設置類別並準備預測...",
        "auto_label_predicting": "執行目標圖像預測...",
        "auto_label_completed_success": "✅ 自動標註完成！\n成功處理了 {0}/{1} 張圖片",
        "auto_label_completed_partial": "⚠️ 自動標註完成\n成功處理了 {0}/{1} 張圖片",
        "auto_label_failed_error": "❌ 自動標註失敗\n錯誤：{0}",
        "delete_class": "刪除類別",
        "confirm_delete_class_title": "確認刪除類別",
        "confirm_delete_class_msg": "你確定要刪除類別 '{0}' 嗎？\n此操作無法撤銷。",
        "delete_related_annotations_title": "刪除相關標註",
        "delete_related_annotations_msg": "在當前圖片中發現 {0} 個使用類別 '{1}' 的標註。\n你要一起刪除這些標註嗎？",
        "auto_label_current_image": "自動標註當前圖片",
        "auto_label_current_title": "自動標註當前圖片",
        "auto_label_current_confirm": "使用當前圖片的標註作為提示來自動標註同張圖片？\n這將幫助在當前圖片中找到相似的物體。",
        "no_current_image": "沒有加載當前圖片",
        "current_image_no_annotations": "當前圖片沒有標註可用作提示",
        "failed_to_build_visuals": "無法從當前標註構建視覺提示",
        "replace_annotations_title": "替換標註",
        "replace_annotations_msg": "你要用新的預測結果替換現有標註嗎？\n選擇'否'將新預測添加到現有標註中。",
        "auto_label_current_success": "當前圖片自動標註完成！\n添加了 {0} 個新標註。",
        "switch_project_title": "切換項目",
        "switch_project_confirm": "當前工作可能會丟失。你確定要切換到新項目嗎？",
        "project_loaded": "項目 '{0}' 已加載，包含 {1} 張圖片",
        "refresh_data": "刷新數據",
        "refresh_data_tooltip": "刷新項目數據並重新掃描標註文件",
        "project_info": "項目信息",
        "current_project": "當前項目",
        "total_images": "總圖片數",
        "labeled_images": "已標註圖片",
        "unlabeled_images": "未標註圖片",
        "no_labeled_images_found": "在當前項目中沒有找到已標註的圖片",
        "objects": "個對象",
        "refresh_complete": "刷新完成",
        "refresh_complete_msg": "在當前項目中找到 {0} 張已標註的圖片",
    },
    "fr": {
        "open": "Ouvrir",
        "save": "Enregistrer",
        "next_image": "Image suivante",
        "prev_image": "Image précédente",
        "delete": "Supprimer les boîtes sélectionnées",
        "auto_save": "Enregistrement auto",
        "label_propagation": "Propagation des étiquettes",
        "output_format": "Format de sortie",
        "classes": "Classes",
        "ready": "Prêt",
        "no_classes_file": "Aucun classes.txt trouvé dans ce dossier.\nVoulez-vous sélectionner un fichier txt existant comme fichier de classes ?\nOui pour sélectionner, Non pour saisir manuellement.",
        "yes": "Oui",
        "no": "Non",
        "hotkeys_help": "Raccourcis clavier",
        "quit": "Quitter",
        "file_menu": "Fichier(&F)",
        "load_label_file": "Charger fichier d'étiquettes (ex. .txt)",
        "help_menu": "Aide(&H)",
        "hotkeys_menu": "Raccourcis(&K)",
        "about_menu": "À propos de BakuAI AS(&A)",
        "hotkeys_title": "Raccourcis clavier",
        "hotkeys_list": "Liste des raccourcis：",
        "next_image_hotkey": "Image suivante",
        "prev_image_hotkey": "Image précédente",
        "save_hotkey": "Enregistrer les annotations",
        "open_hotkey": "Ouvrir le répertoire",
        "delete_hotkey": "Supprimer les boîtes sélectionnées",
        "quit_hotkey": "Quitter",
        "label_propagation_hotkey": "Basculer la copie des étiquettes",
        "multi_select_hotkey": "Sélection multiple de boîtes",
        "undo_hotkey": "Annuler (par image)",
        "redo_hotkey": "Rétablir (par image)",
        "about_title": "À propos de BakuAI",
        "version": "Version",
        "copyright": "Tous droits réservés",
        "website": "Site web officiel",
        "software_description": "Ce logiciel est utilisé pour l'étiquetage d'images, prend en charge les formats YOLO/VOC/COCO",
        "debug_info": "Informations de débogage",
        "current_working_dir": "Répertoire de travail actuel",
        "dist_dir_contents": "Contenu du répertoire Dist",
        "debug_info_end": "Fin des informations de débogage",
        "class_save_failed": "Échec de l'enregistrement de la classe",
        "failed_to_write_classes": "Impossible d'écrire classes.txt : {0}",
        "save_error": "Erreur de sauvegarde",
        "failed_to_save_yolo": "Échec de l'enregistrement des annotations YOLO :\n{0}",
        "edit_label": "Modifier l'étiquette",
        "enter_new_label": "Entrez une nouvelle étiquette :",
        "data_aug_menu": "Augmentation de Données(&D)",
        "data_aug_title": "Paramètres d'Augmentation par Lot",
        "saturation": "Saturation",
        "contrast": "Contraste",
        "brightness": "Luminosité",
        "rotation": "Rotation (degrés)",
        "flip_ud": "Retourner Haut-Bas",
        "flip_lr": "Retourner Gauche-Droite",
        "apply": "Appliquer",
        "cancel": "Annuler",
        "reset": "Réinitialiser",
        "preview": "Aperçu",
        "aug_per_image": "Augmentations par image",
        "output_folder": "Dossier de sortie",
        "select_folder": "Sélectionner le dossier",
        "processing": "Traitement...",
        "aug_complete": "Augmentation terminée",
        "aug_progress": "Traitement de {0}/{1} images",
        "aug_success": "{0} images augmentées avec succès",
        "aug_error": "Erreur lors de l'augmentation",
        "preserve_original": "Conserver les fichiers originaux",
        "aug_settings": "Paramètres d'augmentation",
        "random_rotation": "Plage de rotation aléatoire",
        "random_brightness": "Plage de luminosité aléatoire",
        "random_contrast": "Plage de contraste aléatoire",
        "random_saturation": "Plage de saturation aléatoire",
        "flip_options": "Options de retournement",
        "warning": "Avertissement",
        "no_image": "Aucune image chargée. Veuillez d'abord ouvrir une image.",
        "auto_label_menu": "Étiquetage Automatique(&A)",
        "auto_label_title": "Étiquetage Automatique avec Prompt Visuel",
        "select_prompt_images": "Sélectionner les images prompt",
        "select_target_image": "Sélectionner l'image cible",
        "no_prompt_images": "Aucune image prompt sélectionnée",
        "no_target_image": "Aucune image cible sélectionnée",
        "auto_label_error": "Étiquetage automatique échoué",
        "auto_label_success": "Étiquetage automatique terminé avec succès",
        "error_no_class_list": "Erreur : liste de classes non trouvée dans la fenêtre principale (label_hist)",
        "error_target_image_not_exist": "Erreur : l'image cible n'existe pas : {0}",
        "error_prompt_image_not_exist": "Erreur : l'image prompt n'existe pas : {0}",
        "processing_vp_auto_label": "Traitement de l'étiquetage automatique avec prompt visuel...",
        "converting_annotations": "Conversion des annotations...",
        "executing_prediction": "Exécution de la prédiction...",
        "warning_unknown_class_id": "Avertissement : ID de classe inconnu {0}",
        "error_adding_bbox": "Erreur lors de l'ajout de la boîte englobante : {0}",
        "error_loading_annotation": "Échec du chargement du fichier d'annotation : {0}",
        "info_using_pascal_voc_reader": "Info : utilisation du lecteur Pascal VOC",
        "info_using_yolo_reader": "Info : utilisation du lecteur YOLO",
        "warning_no_compatible_reader": "Avertissement : aucun lecteur d'annotations compatible trouvé",
        "warning_no_annotation_file": "Avertissement : fichier d'annotation non trouvé : {0}",
        "warning_no_valid_annotations": "Avertissement : aucune annotation valide trouvée : {0}",
        "warning_unknown_class": "Avertissement : classe inconnue {0}",
        "warning_invalid_bbox_coords": "Avertissement : coordonnées de boîte englobante invalides [{0}, {1}, {2}, {3}]",
        "warning_cannot_get_bbox_coords": "Avertissement : impossible d'obtenir les coordonnées de la boîte englobante, annotation ignorée",
        "error_processing_annotation": "Erreur lors du traitement du fichier d'annotation {0} : {1}",
        "auto_label_completed": "Étiquetage automatique terminé : {0} annotations ajoutées",
        "skipped_invalid_labels": ", {0} annotations invalides ignorées",
        "auto_label_completed_no_valid_labels": "Étiquetage automatique terminé, mais aucune annotation valide ajoutée",
        "auto_label_failed": "Étiquetage automatique échoué : {0}",
        "enable_magnifier": "Activer la loupe",
        "current_zoom": "Zoom actuel : {0}x",
        "color_legend": "Légende des couleurs",
        "load_custom_classes": "Charger classes.txt personnalisé",
        "to": "à",
        "unknown": "inconnu",
        "error": "Erreur",
        "auto_label_all_unlabeled": "Étiqueter automatiquement toutes les images non étiquetées",
        "label_propagation_activated": "Propagation des étiquettes activée",
        "label_propagation_disabled": "Propagation des étiquettes désactivée",
        "viewed": "Vu",
        "index": "Index",
        "total": "Total",
        "error_current_dir_not_set": "Erreur : répertoire actuel non défini.",
        "bakuai_label_tool": "Outil d'Étiquetage BakuAI",
        "open_image_folder_to_start": "Aprire le dossier d'images pour commencer",
        "logo_not_found_using_default": "Logo non trouvé à {0}, utilisation par défaut.",
        "yoloe_wrapper_not_initialized": "YOLOEWrapper 未初始化，请确保已加载类别文件",
        "batch_auto_label_start": "開始批量自動標註...",
        "batch_auto_label_complete": "批量自動標註完成",
        "select_prompt_images_first": "請先選擇提示圖片（左側綠色的圖片）",
        "overwrite_labeled_images": "覆蓋已標註圖片？",
        "overwrite_labeled_images_question": "你要覆蓋已經標註的圖片嗎？",
        "all_images_labeled": "所有圖片都已標註，無需自動標註。",
        "auto_label_progress_title": "自動標註進度",
        "auto_label_preparing": "準備自動標註...",
        "auto_label_validating": "驗證輸入文件...",
        "auto_label_building_vpe": "構建視覺提示編碼器...",
        "auto_label_setting_classes": "設置類別並準備預測...",
        "auto_label_predicting": "執行目標圖像預測...",
        "auto_label_completed_success": "✅ 自動標註完成！\n成功處理了 {0}/{1} 張圖片",
        "auto_label_completed_partial": "⚠️ 自動標註完成\n成功處理了 {0}/{1} 張圖片",
        "auto_label_failed_error": "❌ 自動標註失敗\n錯誤：{0}",
        "delete_class": "刪除類別",
        "confirm_delete_class_title": "確認刪除類別",
        "confirm_delete_class_msg": "你確定要刪除類別 '{0}' 嗎？\n此操作無法撤銷。",
        "delete_related_annotations_title": "刪除相關標註",
        "delete_related_annotations_msg": "在當前圖片中發現 {0} 個使用類別 '{1}' 的標註。\n你要一起刪除這些標註嗎？",
        "auto_label_current_image": "自動標註當前圖片",
        "auto_label_current_title": "自動標註當前圖片",
        "auto_label_current_confirm": "使用當前圖片的標註作為提示來自動標註同張圖片？\n這將幫助在當前圖片中找到相似的物體。",
        "no_current_image": "沒有加載當前圖片",
        "current_image_no_annotations": "當前圖片沒有標註可用作提示",
        "failed_to_build_visuals": "無法從當前標註構建視覺提示",
        "replace_annotations_title": "替換標註",
        "replace_annotations_msg": "你要用新的預測結果替換現有標註嗎？\n選擇'否'將新預測添加到現有標註中。",
        "auto_label_current_success": "當前圖片自動標註完成！\n添加了 {0} 個新標註。",
        "switch_project_title": "切換項目",
        "switch_project_confirm": "當前工作可能會丟失。你確定要切換到新項目嗎？",
        "project_loaded": "項目 '{0}' 已加載，包含 {1} 張圖片",
        "refresh_data": "刷新數據",
        "refresh_data_tooltip": "刷新項目數據並重新掃描標註文件",
        "project_info": "項目信息",
        "current_project": "當前項目",
        "total_images": "總圖片數",
        "labeled_images": "已標註圖片",
        "unlabeled_images": "未標註圖片",
        "no_labeled_images_found": "在當前項目中沒有找到已標註的圖片",
        "objects": "個對象",
        "refresh_complete": "刷新完成",
        "refresh_complete_msg": "在當前項目中找到 {0} 張已標註的圖片",
    },
}

# 自動偵測系統語言
def get_system_language():
    # 如果设置了手动语言，优先使用
    if 'MANUAL_LANG' in globals():
        return MANUAL_LANG
    
    # 尝试从配置文件读取语言设置
    try:
        import sys
        import os
        # 添加项目根目录到路径
        project_root = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
        if project_root not in sys.path:
            sys.path.insert(0, project_root)
        
        from language_config import LANGUAGE
        if LANGUAGE in ['en', 'zh-tw', 'zh-cn', 'ja', 'it', 'de', 'no', 'es', 'fr']:
            return LANGUAGE
    except ImportError:
        pass  # 配置文件不存在，继续使用系统检测
    except Exception as e:
        print(f"Error reading language config: {e}")
    
    try:
        # 嘗試多種方法獲取系統語言
        if sys.platform == 'darwin':  # macOS
            import subprocess
            try:
                lang = subprocess.check_output(['defaults', 'read', 'NSGlobalDomain', 'AppleLanguages']).decode('utf-8')
                if 'zh-Hant' in lang or 'zh_TW' in lang:
                    return 'zh-tw'
                elif 'zh-Hans' in lang or 'zh_CN' in lang:
                    return 'zh-cn'
            except:
                pass
        elif sys.platform == 'win32':  # Windows
            import ctypes
            windll = ctypes.windll.kernel32
            try:
                lang = locale.windows_locale[windll.GetUserDefaultUILanguage()]
                if lang.startswith('zh_TW'):
                    return 'zh-tw'
                elif lang.startswith('zh_CN'):
                    return 'zh-cn'
            except:
                pass
        
        # 如果上述方法都失敗，使用 locale
        try:
            lang = locale.getdefaultlocale()[0]
            if lang:
                if lang.startswith('zh_TW'):
                    return 'zh-tw'
                elif lang.startswith('zh_CN'):
                    return 'zh-cn'
                elif lang.startswith('ja'):
                    return 'ja'
                elif lang.startswith('it'):
                    return 'it'
                elif lang.startswith('de'):
                    return 'de'
                elif lang.startswith('no') or lang.startswith('nb') or lang.startswith('nn'):
                    return 'no'
                elif lang.startswith('ko'):
                    return 'ko'
                elif lang.startswith('es'):
                    return 'es'
                elif lang.startswith('fr'):
                    return 'fr'
        except:
            pass
            
        # 如果所有方法都失敗，檢查環境變數
        try:
            lang = os.environ.get('LANG', '').split('.')[0]
            if lang.startswith('zh_TW'):
                return 'zh-tw'
            elif lang.startswith('zh_CN'):
                return 'zh-cn'
        except:
            pass
            
    except Exception as e:
        print(f"Language detection error: {str(e)}")
    
    return 'en'  # 預設使用英文

# 使用新的語言偵測函數
LANG = get_system_language()

def tr(key):
    return TRANSLATIONS.get(LANG, TRANSLATIONS['en']).get(key, key) 